### ISSUE TITLE
Aggregate relations do not yet support output mapping changes

### ISSUE THREAD

**Issue by mortbopet** [substrait-io/substrait-cpp#121]
Unfortunately, my queries seem to hit the [Aggregate relations do not yet support output mapping changes](https://github.com/substrait-io/substrait-cpp/blob/main/src/substrait/textplan/converter/InitialPlanProtoVisitor.cpp#L634) error. However, for my given usecase, sufficient information is retained/parsed if i just comment out the following lines:
https://github.com/substrait-io/substrait-cpp/blob/03760889013210041038398e595639d04b4f1cc3/src/substrait/textplan/converter/InitialPlanProtoVisitor.cpp#L632-L636

Now that may be bad... but again, works for my usecase. My question is therefore - is there a way to opt-in to this feature, or make the error recoverable, s.t. users (like me) can use upstream substrait-cpp?

**Comment by EpsilonPrime** [comment]
I put that check in there because it's important to handle (it affects the rest of the plan) but I didn't see any cases where folks were using it (in fact, some systems don't even support emits in aggregations yet).  I'll make a stab at adding this missing feature.

**Comment by mortbopet** [comment]
> I put that check in there because it's important to handle (it affects the rest of the plan) but I didn't see any cases where folks were using it (in fact, some systems don't even support emits in aggregations yet). I'll make a stab at adding this missing feature.

Much appreciated! 🙏

**Comment by EpsilonPrime** [comment]
Progress update:  I have binary to text conversion working correctly but there are one or two small bugs in the text to binary parsing that I need to fix.  Shouldn't be more than another day.

**Comment by EpsilonPrime** [comment]
Please let me know if I missed anything.

**Comment by mortbopet** [comment]
So far looks like the fix is working for my use-case. Thank you very much for looking into this!
