### ISSUE TITLE
How can i use this to transform a sql to plan(or something)?

### ISSUE THREAD

**Issue by Ecthlion** [substrait-io/substrait-cpp#88]
I read the README.md and did as it said, and i got a dir named build-Debug. There are two exe files in substrait-cpp/build-Debug/debug, but i do not know what should i give as a input file, and what the exe file will export. Can someone tell me how to use this project to convert SQL into a plan? I would greatly appreciate your help

**Comment by EpsilonPrime** [comment]
These tools convert between plan formats.  If you want to convert SQL I suggest you take a look at Isthmus.

**Comment by Ecthlion** [comment]
> These tools convert between plan formats. If you want to convert SQL I suggest you take a look at Isthmus.

Thank you for your reply. I just want to get a parser and a planner written by c++, but it seems difficult.
